name: 🔒 Security Vulnerability
description: ⚠️ НЕ ИСПОЛЬЗУЙТЕ для реальных уязвимостей! Прочитайте SECURITY.md
title: "⚠️ ВНИМАНИЕ: Прочитайте Security Policy!"
labels: ["security"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ⚠️ СТОП! НЕ СОЗДАВАЙТЕ ПУБЛИЧНЫЙ ISSUE ДЛЯ УЯЗВИМОСТЕЙ!
        
        ## Если вы нашли уязвимость в безопасности:
        
        **НЕ публикуйте её здесь!** Это может подвергнуть опасности всех пользователей.
        
        ### ✅ Правильный способ:
        
        1. **Прочитайте нашу [Security Policy](../../security/policy)**
        2. **Отправьте приватный отчет через [Security Advisories](../../security/advisories/new)**
        3. **Или напишите нам на email: info@yeb-ich.com**
        
        ---
        
        ## Эта форма только для:
        
        - ❓ Вопросов о безопасности (не уязвимостей)
        - 📚 Предложений по улучшению документации безопасности
        - 🛡️ Общих вопросов о политике безопасности

  - type: dropdown
    id: type
    attributes:
      label: Тип обращения
      description: Выберите, что именно вы хотите обсудить
      options:
        - 🚨 Я нашел реальную уязвимость (ЗАКРОЙТЕ ЭТОТ ISSUE И ИСПОЛЬЗУЙТЕ SECURITY.MD!)
        - ❓ Вопрос о политике безопасности
        - 📚 Предложение по документации безопасности
        - 🛡️ Общий вопрос о безопасности
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Описание
      description: Опишите ваш вопрос или предложение
      placeholder: |
        Например: "В документации SECURITY.md не указан срок ответа на отчеты"
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: ⚠️ Подтверждение
      options:
        - label: Я прочитал SECURITY.md и понимаю, как правильно сообщать об уязвимостях
          required: true
        - label: Это НЕ отчет о реальной уязвимости
          required: true
